#ifndef _CONSTS_H_
#define _CONSTS_H_

enum{
  NAN_CHECK_CAMERA_WORKING_INIT,
  FUNC_CHECK_CAMERA_WORKING,
  FUNC_GET_FRAME,
  FUNC_GET_VALIDITY_KEY,
  FUNC_ROBUST_TAMPERING,
  FUNC_CHECK_VALIDITY_KEY,
  FUNC_START_HEATMAP,
  FUNC_GET_HEATMAP,
  FUNC_START_ABANDONED,
  FUNC_STOP_AWIROS,
  FUNC_FRS_TEST,
  FUNC_TRACK_OBJECTS,
  FUNC_START_MOTION,
  FUNC_STATE_CHECK,
  FUNC_FOOTFALL_COUNT,
  FUNC_ACTION_ON_APP,
  FUNC_DETECT_PLATE = 16,
  FUNC_RECOGNIZE,
  FUNC_HELMET_VIOLATION,
  FUNC_SIMPLE_CAMERA = 101,
  FUNC_SPEED_DETECTION = 102,
  FUNC_WRONG_WAY = 103,
  //FUNC_TRAIN_MODEL = 105,
  FUNC_TRACK_OBJECTS_WITH_DARKNET = 107,
  FUNC_SPEED_DETECTION_WITH_DARKNET = 108,
  //FUNC_WRONG_WAY_WITH_DARKNET = 110,
  FUNC_WRONG_WAY_WITH_DARKNET = 144,
  //TEMP
  //FUNC_CROWD_COUNT = 120,
  FUNC_CROWD_COUNT = 120,
  FUNC_DEBRIS = 121,
  FUNC_PERSON_COLLAPSE = 122,
  FUNC_REID = 123,
  //FUNC_REID = 9090,
  FUNC_PERSON_LOITERING =150,
  //FUNC_VEHICLE_COUNT = 144,
  FUNC_VEHICLE_COUNT = 110,
  //FUNC_REBEL = 786,
  FUNC_STREET_VIEW_CLASSIFICATION = 147,
  FUNC_GENERAL_COUNT = 201,
  FUNC_FIRE_DETECTION = 4546,
  FUNC_CROWD_PLUS = 1943,
  FUNC_REBEL = 4547,
  //FUNC_ZEBRA_VIOLATION = 7860,
  FUNC_SMOKE_DETECTION = 4949,
  FUNC_HARD_REID = 9090,
  //FUNC_HARD_REID = 123,
  FUNC_REID_MULTIBLOB = 2893,
  FUNC_PARKING_VIOLATION = 106,//456,
  FUNC_PARKING_MANAGER = 457,
  //FUNC_REBEL = 786,
  FUNC_WRONG_WAY_VEHICLE = 112,
  FUNC_WORKER_PROTECTION = 113,
  FUNC_PERSON_COUNT = 6562,
  FUNC_FAISS_TEST = 500,
  //TEMP
  FUNC_NPR_ON_ZEBRA = 9152,
  FUNC_NPR_ON_PARKING = 438,
  FUNC_CAR_DAMAGE = 104,
  FUNC_DYNAMIC_APP = 169,
  FUNC_FACE_COUNT = 6009,
  FUNC_GRAFFITI_DETECTION = 146,
  FUNC_GRIFFIN = 404,
  FUNC_LIVELINESS_DETECTION = 111,
  FUNC_POTHOLE_DETECTION = 145,
  FUNC_START_TAMPERING = 133,
  FUNC_TAILGATE = 870,
  FUNC_OPENCV_MTCNN = 786,
  N_FUNC_ALL_APPS
}; //TODO: make sure that the order is same acroos all branches and commits to be in synv with node

enum class auth_ret_t {
  AUTH_OK,
  KEY_INVALID,
  KEY_EXPIRED,
  N_AUTH_CONST
};

enum class msg_t {
  ERROR,
  DEBUG,
  INFO,
  N_MSG_T
};


static const int app_registry_recheck_time = 2;

#endif // _CONSTS_H_
